
package Presentacion;

import Logica.TorreDeControl;

public class JF_menu extends javax.swing.JFrame {

    private static final TorreDeControl insTDC = new TorreDeControl();
    
    public JF_menu() {
        initComponents();
        btn_listaAvionesEnVuelo.setEnabled(false);
        btn_pistaDespegue.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jB_iniciaSimulacion = new javax.swing.JButton();
        btn_listaAvionesEnVuelo = new javax.swing.JButton();
        lbl_info_avionesEnVuelo = new javax.swing.JLabel();
        lbl_info_avionesEnPistaAterrizaje = new javax.swing.JLabel();
        lbl_info_avionesEnPistaDespegue = new javax.swing.JLabel();
        lbl_info_avionesEnHangar = new javax.swing.JLabel();
        lbl_text_avionesEnVuelo = new javax.swing.JLabel();
        lbl_text_avionesEnPistaAterrizaje = new javax.swing.JLabel();
        lbl_text_avionesEnPistaDespegue = new javax.swing.JLabel();
        lbl_text_avionesEnHangar = new javax.swing.JLabel();
        lbl_info_estado = new javax.swing.JLabel();
        btn_pistaDespegue = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jB_iniciaSimulacion.setText("Inicia Simulación");
        jB_iniciaSimulacion.setPreferredSize(new java.awt.Dimension(140, 50));
        jB_iniciaSimulacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_iniciaSimulacionActionPerformed(evt);
            }
        });

        btn_listaAvionesEnVuelo.setText("Ver Aviones en Vuelo");
        btn_listaAvionesEnVuelo.setPreferredSize(new java.awt.Dimension(140, 50));
        btn_listaAvionesEnVuelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listaAvionesEnVueloActionPerformed(evt);
            }
        });

        lbl_info_avionesEnVuelo.setText("...");

        lbl_info_avionesEnPistaAterrizaje.setText("...");

        lbl_info_avionesEnPistaDespegue.setText("...");

        lbl_info_avionesEnHangar.setText("...");

        lbl_text_avionesEnVuelo.setText("Aviones en vuelo:");

        lbl_text_avionesEnPistaAterrizaje.setText("Aviones en pista de aterrizaje:");

        lbl_text_avionesEnPistaDespegue.setText("Aviones en pista de despegue:");

        lbl_text_avionesEnHangar.setText("Aviones en hangar:");

        lbl_info_estado.setText("...");

        btn_pistaDespegue.setText("Pista de Despegue");
        btn_pistaDespegue.setMaximumSize(new java.awt.Dimension(135, 23));
        btn_pistaDespegue.setMinimumSize(new java.awt.Dimension(135, 23));
        btn_pistaDespegue.setPreferredSize(new java.awt.Dimension(140, 50));
        btn_pistaDespegue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pistaDespegueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jB_iniciaSimulacion, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
                    .addComponent(btn_listaAvionesEnVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_pistaDespegue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_text_avionesEnVuelo)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_info_avionesEnVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_text_avionesEnPistaAterrizaje)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_info_avionesEnPistaAterrizaje, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl_text_avionesEnHangar)
                            .addComponent(lbl_text_avionesEnPistaDespegue))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_info_avionesEnPistaDespegue, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_info_avionesEnHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(46, 46, 46))
            .addComponent(lbl_info_estado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_info_avionesEnVuelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_text_avionesEnVuelo))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_info_avionesEnPistaAterrizaje, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_text_avionesEnPistaAterrizaje))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_info_avionesEnPistaDespegue, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_text_avionesEnPistaDespegue)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB_iniciaSimulacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_listaAvionesEnVuelo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_text_avionesEnHangar)
                        .addComponent(lbl_info_avionesEnHangar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_pistaDespegue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90)
                .addComponent(lbl_info_estado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_iniciaSimulacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_iniciaSimulacionActionPerformed
        
        lbl_info_estado.setText(" " + insTDC.creaBD() + " aviones agregados");
        insTDC.distribuyeAviones();
        insTDC.imprimeEnConsola();
        
        lbl_info_avionesEnVuelo.setText(insTDC.imprimeAvionesVolando2());
        lbl_info_avionesEnPistaAterrizaje.setText(insTDC.imprimeAvionesPistaAterrizaje2());
        lbl_info_avionesEnPistaDespegue.setText(insTDC.imprimeAvionesPistaDespegue2());
        lbl_info_avionesEnHangar.setText(insTDC.imprimeAvionesHangar2());
        
        jB_iniciaSimulacion.setEnabled(false);
        btn_listaAvionesEnVuelo.setEnabled(true);
        btn_pistaDespegue.setEnabled(true);
        
    }//GEN-LAST:event_jB_iniciaSimulacionActionPerformed

    private void btn_listaAvionesEnVueloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listaAvionesEnVueloActionPerformed
        
        JF_listaAvionesEnVuelo insLAV = new JF_listaAvionesEnVuelo();
        insLAV.setLocationRelativeTo(null);
        insLAV.setVisible(true);
        
        
        
    }//GEN-LAST:event_btn_listaAvionesEnVueloActionPerformed

    private void btn_pistaDespegueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pistaDespegueActionPerformed
        JF_PistaDespegue insPD = new JF_PistaDespegue();
        insPD.setLocationRelativeTo(null);
        insPD.setVisible(true);
    }//GEN-LAST:event_btn_pistaDespegueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JF_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JF_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JF_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JF_menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JF_menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_listaAvionesEnVuelo;
    private javax.swing.JButton btn_pistaDespegue;
    private javax.swing.JButton jB_iniciaSimulacion;
    private javax.swing.JLabel lbl_info_avionesEnHangar;
    private javax.swing.JLabel lbl_info_avionesEnPistaAterrizaje;
    private javax.swing.JLabel lbl_info_avionesEnPistaDespegue;
    private javax.swing.JLabel lbl_info_avionesEnVuelo;
    private javax.swing.JLabel lbl_info_estado;
    private javax.swing.JLabel lbl_text_avionesEnHangar;
    private javax.swing.JLabel lbl_text_avionesEnPistaAterrizaje;
    private javax.swing.JLabel lbl_text_avionesEnPistaDespegue;
    private javax.swing.JLabel lbl_text_avionesEnVuelo;
    // End of variables declaration//GEN-END:variables
}
